### ISSUE TITLE
Not so good rendering

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#11]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/lister/Lister.js#L70

Better this way for example:

`const { res } = this.props;`  And actually that `res` prop should have a better name

```
<div className={styles.container} onScroll={this.handleScroll}>
   {res.map(element => (
      <Card
                value={element}
                name={element.name}
                episode={element.episode}
                created={element.created}
                type={element.type}
                dimension={element.dimension}
                image={element.image}
     />
  )}
</div>
```

**Comment by donpapitoskey** [comment]
Noted.  Usage of `map` for multiple objects rendering. Also, name of prop `res` changed
