### ISSUE TITLE
Unnecessary conditional blocks

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#12]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/lister/Lister.js#L59

After a `return` the code flow is finished, therefor you don't need `else` or `else if` , you only need just another `if`

**Comment by donpapitoskey** [comment]
Noted.
