### ISSUE TITLE
No spanish name

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#13]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/modal/Modal.js#L11

This variable should not be in spanish. It also can be a `const` actually because arrays in javascript are store as reference values, so if you push a new element to the array, it modifies the array but doesn't change the reference

**Comment by donpapitoskey** [comment]
Noted. However, because I used `map` for the `Auxcard` components rendering
