### ISSUE TITLE
This file is so much overcrowded

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#15]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/redux/searchDuck.js#L1

Choose a better structure.
You can see for example how it is structured on the react native boilerplate

**Comment by donpapitoskey** [comment]
Noted. ActionTypes, Actions and Reducer separated in different files
