### ISSUE TITLE
[minor] Unnecesary ternary

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/PUZZLE.Challenge#19]
In this case, it would be wiser to use the `||` operator, to choose the first one, or the second one if the former is unavailable

https://github.com/donpapitoskey/PUZZLE.Challenge/blob/44ed4502fd34dc7e5cb7212cce1f114d116508b1/src/components/auxcard/Auxcard.js#L23

**Comment by donpapitoskey** [comment]
Solved. Ternaries with null replaced with double ampersand.
