### ISSUE TITLE
No need to be `let`

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#2]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/index.js#L17

I think all the declarations in this file can be just `const`. None of the elements are being actually reassigned.

**Comment by donpapitoskey** [comment]
Understood. So when a variable is never again reasigned is the perfect moment to use  `const`
