### ISSUE TITLE
[CRITICAL] Usage of shorthand properties

### ISSUE THREAD

**Issue by ale1313** [donpapitoskey/PUZZLE.Challenge#20]
Keep in mind that you should take advantage as much as possible for the shorthand properties, as they can save you multiple lines of code. Examples of them are `border`, `padding`, `margin`, etc

https://github.com/donpapitoskey/PUZZLE.Challenge/blob/44ed4502fd34dc7e5cb7212cce1f114d116508b1/src/components/auxcard/auxcard.module.css#L2

**Comment by donpapitoskey** [comment]
Noted.
