### ISSUE TITLE
Put 'pages' folder outside the 'components' folder

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#3]
```
:
src
|--components
|--pages
|--redux
:
```

**Comment by edgarbonillag** [comment]
Edit: I just saw that `pages` is a component, not a folder for pages or screens. I think you should better choose another name for that component

**Comment by donpapitoskey** [comment]
Understood. So `pages` contain an specific route and have an URL
