### ISSUE TITLE
Simplify expression

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#4]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/home/Home.js#L42

This can be simplified as `let windowHeight =  window ? window.innerHeight : 0`
I also don't see the need to use `let` here.

**Comment by donpapitoskey** [comment]
Noted. Since the window information is constant, I should keep it `const`
