### ISSUE TITLE
Only one component per file

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#5]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/card/Card.js#L8

https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/card/Card.js#L59

Ideally have only one component per file, separate the ´Auxcard´ in another file or even folder

**Comment by donpapitoskey** [comment]
Done. Component retrieved and stored in a different file with own style file
