### ISSUE TITLE
Use destructuring

### ISSUE THREAD

**Issue by edgarbonillag** [donpapitoskey/PUZZLE.Challenge#6]
https://github.com/donpapitoskey/PUZZLE.Challenge/blob/acde2e89293ff5102936c82a4892f07960f5b3aa/src/components/card/Card.js#L28

`this.props` and `this.state` everywhere (bad)

Use destructuring for cleaner code

**Comment by donpapitoskey** [comment]
Noted. Destructure of `this.props` and `this.state` applied along the whole project
